(()=>{
 const $=id=>document.getElementById(id);let token='',group=null,records=[];
 async function api(action,data){const r=await fetch('api.php?action='+action,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json','X-CSRF-Token':token}:{},body:data?JSON.stringify(data):undefined});const result=await r.json();if(!r.ok)throw Error(result.message);return result;}
 function report(error){$('status').textContent=error.message;}
 async function session(){const s=await api('session');token=s.csrf;$('auth').hidden=!!s.user;$('workspace').hidden=!s.user;if(s.user){$('welcome').textContent='Sesión de '+s.user.name;await groups();}}
 async function groups(){const data=await api('groups');$('groups').replaceChildren();for(const g of data.groups){const li=document.createElement('li'),b=document.createElement('button');b.textContent=g.nombre;b.addEventListener('click',()=>open(Number(g.id)).catch(report));li.append(b);$('groups').append(li);}}
 async function open(id){const data=await api('group&id='+id);group=id;$('group').hidden=false;$('group-title').textContent=data.group.nombre;$('code').textContent='Invitación: '+data.group.codigo;$('members').replaceChildren();for(const m of data.members){const li=document.createElement('li');li.textContent=m.nombre;$('members').append(li);}$('saved').replaceChildren();for(const s of data.simulations){const a=document.createElement('article'),h=document.createElement('h4'),p=document.createElement('pre');h.textContent='Sim '+s.simulador_id+' · '+s.guardado_en;p.textContent=JSON.stringify({parametros:JSON.parse(s.parametros),resultado:JSON.parse(s.resultado)},null,2);a.append(h,p);$('saved').append(a);}loadRecords();}
 function loadRecords(){let storage;try{storage=window.localStorage;}catch{}records=SimRegistry.create($('sim').value,storage).list();$('record').replaceChildren();for(const [i,r]of records.entries()){const o=document.createElement('option');o.value=i;o.textContent='Registro '+r.id+' · '+r.savedAt;$('record').append(o);}preview();}
 function preview(){const r=records[Number($('record').value)];$('preview').textContent=r?JSON.stringify(r.snapshot,null,2):'No hay registros locales de este simulador.';$('save').disabled=!r;}
 for(let n=1;n<=13;n++){const o=document.createElement('option');o.value=String(n).padStart(2,'0');o.textContent='Simulador '+o.value;$('sim').append(o);}
 $('sim').addEventListener('change',loadRecords);$('record').addEventListener('change',preview);
 $('account').addEventListener('submit',async e=>{e.preventDefault();try{const data=Object.fromEntries(new FormData(e.target)),action=e.submitter.name;const result=await api(action,data);e.target.reset();$('status').textContent=result.message||'Sesión iniciada.';await session();}catch(err){report(err);}});
 for(const action of ['create','join'])$(action).addEventListener('submit',async e=>{e.preventDefault();try{const r=await api(action,Object.fromEntries(new FormData(e.target)));e.target.reset();await groups();await open(r.id);$('status').textContent='Grupo actualizado.';}catch(err){report(err);}});
 $('save').addEventListener('click',async()=>{const r=records[Number($('record').value)];if(!r)return;try{$('save').disabled=true;await api('save',{grupo_id:group,simulador_id:$('sim').value,parametros:r.snapshot.parameters,resultado:r.snapshot.results});$('status').textContent='Captura guardada en el grupo.';await open(group);}catch(err){report(err);}finally{preview();}});
 $('leave').addEventListener('click',async()=>{try{await api('leave',{grupo_id:group});group=null;$('group').hidden=true;await groups();}catch(err){report(err);}});
 $('logout').addEventListener('click',async()=>{try{await api('logout',{});group=null;$('group').hidden=true;await session();$('status').textContent='Sesión cerrada.';}catch(err){report(err);}});
 session().catch(report);
})();
