const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
class El{constructor(tag='div'){this.tag=tag;this.children=[];this.events={};this.style={};this.attributes={};this.value='';this.classList={contains:()=>true};}append(...a){this.children.push(...a);}replaceChildren(...a){this.children=[...a];}setAttribute(k,v){this.attributes[k]=v;}addEventListener(k,v){this.events[k]=v;}set innerHTML(v){throw Error('Unsafe HTML');}}
const walk=(e,tag)=>[...(e.tag===tag?[e]:[]),...e.children.flatMap(c=>walk(c,tag))];
for(const route of fs.readdirSync('simuladores')){const id=route.slice(0,2);if(!/^\d\d$/.test(id))continue;
 const data=new Map(),storage={getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)};
 function page(){const body=new El('body');body.dataset={simId:id};const nav=new El('nav'),sim=new El();sim.parentElement=body;const ids={'tab-sim':sim};
 const get=k=>ids[k]??=new El();get('panel-prefijos').style.display='block';get('pref-valor').value='2';get('pref-origen').value='3';get('pref-destino').value='0';get('eff-in').value='100';get('eff-out').value='80';get('eff-kind').value='J';
 let ready,capture;const ctx=vm.createContext({console,document:{body,getElementById:get,querySelector:()=>nav,querySelectorAll:()=>[],createElement:t=>new El(t),addEventListener:(k,fn)=>{ready=fn;}},window:{localStorage:storage},setTimeout:()=>{},setTab:()=>{},SimGroups:{bind:fn=>{capture=fn;}}});
 for(const f of ['js/sim-common.js','simuladores/'+route+'/js/engine.js','js/sim-registry.js','js/sim-records-ui.js'])vm.runInContext(fs.readFileSync(f,'utf8'),ctx);vm.runInContext('if(Engine.init)Engine.init();if(Engine.calcular)Engine.calcular();',ctx);ready();return {body,nav,ctx,capture,store:vm.runInContext(`SimRegistry.create('${id}',window.localStorage)`,ctx)};}
 let p=page();const quick=p.nav.children.find(e=>e.textContent==='Guardar registro');quick.events.click();assert.equal(p.store.list().length,0,'loaded stores are independent snapshots');let saved=JSON.parse(data.values().next().value);assert.equal(saved.records.length,1,route);assert.ok(walk(p.body,'th').some(e=>e.scope==='colgroup'));const snapshot=JSON.stringify(saved.records[0].snapshot);
 const e=vm.runInContext('Engine',p.ctx);if(e.seekTo)for(let n=0;n<20;n++)e.seekTo(n/10);assert.equal(JSON.parse(data.values().next().value).records.length,1,'seek never saves');assert.equal(JSON.stringify(JSON.parse(data.values().next().value).records[0].snapshot),snapshot);
 p=page();assert.equal(p.store.list().length,1,'reload');const remove=walk(p.body,'button').find(e=>e.textContent==='Eliminar');remove.events.click();assert.equal(JSON.parse(data.values().next().value).records.length,0,'delete');const again=p.nav.children.find(e=>e.textContent==='Guardar registro');again.events.click();again.events.click();walk(p.body,'button').find(e=>e.textContent==='Limpiar registros').events.click();assert.equal(JSON.parse(data.values().next().value).records.length,0,'clear');data.set(p.store.key,'{broken');p=page();assert.equal(p.store.list().length,0,'corrupt load');
}
console.log('PASS: all 13 capture adapters, grouped headers, save/delete/clear/reload/corrupt storage and seek isolation.');
