<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SIM 13 — Llanta compuesta</title>
<link rel="stylesheet" href="../../css/sim-base.css"><link rel="stylesheet" href="../../css/accessibility.css"><link rel="stylesheet" href="../../css/registry.css"><link rel="stylesheet" href="style.css"></head>
<body data-sim-id="13"><header class="sim-header"><span class="sim-badge">SIM #13</span><div class="sim-titles"><h1>Llanta compuesta</h1><span>Momento de inercia de tres cuerpos coaxiales</span></div><nav class="sim-nav"><button class="nav-btn active" data-tab="sim">▶ Simulador</button><button class="nav-btn" data-tab="formulas">∑ Fórmulas</button><a class="nav-btn" href="../../index.php">← Portal</a></nav></header>
<div id="tab-sim" class="tab active"><div class="sim-layout"><aside class="panel-left"><div class="ps"><label for="inp-R_h">Radio exterior Rh (m)</label><input id="inp-R_h" data-param="R_h" min="0.000001" max="20" type="number" step="any" value="0.33"></div><div class="ps"><label for="inp-R_ext">Radio intermedio Re (m)</label><input id="inp-R_ext" data-param="R_ext" min="0.000001" max="20" type="number" step="any" value="0.305"></div><div class="ps"><label for="inp-R_int">Radio interior Ri (m)</label><input id="inp-R_int" data-param="R_int" min="0" max="20" type="number" step="any" value="0.165"></div><div class="ps"><label for="inp-tp">Grosor de cada pared tp (m)</label><input id="inp-tp" data-param="tp" min="0.000001" max="20" type="number" step="any" value="0.00635"></div><div class="ps"><label for="inp-w">Ancho total w (m)</label><input id="inp-w" data-param="w" min="0.000001" max="20" type="number" step="any" value="0.2"></div><div class="ps"><label for="inp-rho">Densidad ρ (kg/m³)</label><input id="inp-rho" data-param="rho" min="0.000001" max="1000000" type="number" step="any" value="1100"></div><div class="ps"><label for="inp-omega">Velocidad angular ω (rad/s)</label><input id="inp-omega" data-param="omega" min="-10000" max="10000" type="number" step="any" value="8"></div><p id="input-error" role="alert"></p><p>0 ≤ Ri &lt; Re &lt; Rh; 0 &lt; 2tp ≤ w. Densidad positiva.</p></aside>
<main class="panel-center"><div class="temporal-scene"><canvas id="canvasMain"></canvas></div></main>
<aside class="panel-right"><h2>Resultados</h2><div id="results"></div><p>Cálculo estático. ω determina K; no se simula evolución temporal. Su signo no cambia la energía.</p><p>Modelo ideal homogéneo: no incluye aro metálico, aire, radios ni buje.</p></aside></div></div>
<section id="tab-formulas" class="tab registry-panel"><?php require __DIR__.'/php/formulas.php'; ?></section>
<script src="../../js/sim-common.js"></script><script src="../../js/canvas-common.js"></script><script src="js/engine.js"></script><script src="js/render.js"></script><script src="js/ui.js"></script><script src="../../js/accessibility.js"></script><script src="../../js/sim-registry.js"></script><script src="../../js/sim-groups.js"></script>
<script src="../../js/sim-records-ui.js"></script></body></html>
